/**
 * A do nothing class that let's me stick a link to the {@link [github repo](https://github.com/no-stack-dub-sack/apexdox-vs-code)} in here!
 * @author Peter Weinberg
 * @since Spring 2019
 * @see https://github.com/no-stack-dub-sack/apexdox-vs-code
 * @group Global Utils
 */
public with sharing class ApexDox {

    /**
     * Is ApexDox VS Code cool?
     * @returns Absolutely!
     */    
    public static boolean isCool() {
        return true;
    }
}
